import Head from 'next/head'
import SiteMenu from '../components/Menu'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* ================= Nav =============================== */}

      <SiteMenu />
      <main className={styles.main}>

      </main>

      <footer className={styles.footer}>

        <span className={styles.logo}>
          {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
        </span>

      </footer>
    </div >
  )
}
